server:
  port: 8080
  servlet:
    context-path: /app

logging:
  level:
    root: INFO

propertyholder:
  defaultTtlInDays: 90
  maxTtlInDaysAllowed: 720
  shortUrlLength: 8

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/URL_Shortener